# Generated by Django 4.2.20 on 2025-07-04 06:52

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='defaults/default-img.png', upload_to=chat.models.uuid_upload_to),
        ),
    ]
