# Generated by Django 4.2.20 on 2025-07-03 16:31

import chat.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=chat.models.HashedImageField(default='defaults/default-img.png', upload_to='users/'),
        ),
    ]
